"use client";

import { useMemo, useState } from "react";
import { useSociety } from "@/lib/store";
import { findDuplicates, parseContributorList } from "@/lib/parse-list";
import { amountInWords, financialYear, toWhatsAppNumber } from "@/lib/receipt";
import { money, shortDate, toDateInput } from "@/lib/format";
import {
  renderReceiptPng,
  shareReceiptImage,
  type ReceiptImageData,
} from "@/lib/receipt-image";
import { Button, Card, EmptyState, Field, PageHeader, SectionTitle, useToast } from "@/components/ui";

const PLACEHOLDER = `1. Anand Pr – ₹1,100
2. Rajesh U – ₹1,111
26. Anup Deo (N-130) – ₹501`;

/**
 * Turns a pasted collection list into receipts that can be printed or sent.
 *
 * Committees keep these lists in WhatsApp and spreadsheets already, and writing
 * out sixty-nine receipts by hand is the job nobody wants. Paste, check, send.
 */
export default function BulkReceiptsPage() {
  const { data, canCollect } = useSociety();
  const toast = useToast();

  const [text, setText] = useState("");
  const [startNo, setStartNo] = useState(1);
  const [date, setDate] = useState(toDateInput(new Date().toISOString()));
  /** Mobile numbers keyed by receipt number, filled in as they're collected. */
  const [numbers, setNumbers] = useState<Record<string, string>>({});
  const [sent, setSent] = useState<Record<string, true>>({});
  const [busy, setBusy] = useState<string | null>(null);

  const parsed = useMemo(() => parseContributorList(text), [text]);
  const duplicates = useMemo(() => findDuplicates(parsed.rows), [parsed.rows]);

  const prefix = data.society.receiptPrefix || "WPC";
  const fy = financialYear(date || new Date().toISOString());

  const receipts: ReceiptImageData[] = useMemo(
    () =>
      parsed.rows.map((row, i) => ({
        receiptNo: `${prefix}/${fy}/${String(startNo + i).padStart(4, "0")}`,
        date: shortDate(date),
        name: row.name,
        wing: row.wing,
        flat: row.flat,
        amount: row.amount,
        societyName: data.society.name,
      })),
    [parsed.rows, prefix, fy, startNo, date, data.society.name],
  );

  if (!canCollect) {
    return (
      <EmptyState
        title="Committee and volunteers only"
        description="Receipts are generated by the people doing the collecting. Ask a committee admin if you need access."
      />
    );
  }

  const caption = (r: ReceiptImageData) =>
    [
      `🙏 Thank you for your contribution to ${data.society.name}.`,
      ``,
      `Receipt ${r.receiptNo}`,
      `Amount: ₹${r.amount.toLocaleString("en-IN")} (${amountInWords(r.amount)})`,
      `Date: ${r.date}`,
    ].join("\n");

  /** Opens the donor's own chat with the receipt typed out. One tap to send. */
  function sendText(r: ReceiptImageData) {
    const number = toWhatsAppNumber(numbers[r.receiptNo] ?? "");
    if (!number) {
      toast("Enter a valid mobile number for this contributor first.", "error");
      return;
    }
    window.open(
      `https://wa.me/${number}?text=${encodeURIComponent(caption(r))}`,
      "_blank",
      "noopener,noreferrer",
    );
    setSent((s) => ({ ...s, [r.receiptNo]: true }));
  }

  /** Shares the receipt picture itself — the design, not a text version. */
  async function sendImage(r: ReceiptImageData) {
    setBusy(r.receiptNo);
    try {
      const blob = await renderReceiptPng(r);
      const how = await shareReceiptImage(blob, r.receiptNo, caption(r));
      setSent((s) => ({ ...s, [r.receiptNo]: true }));
      if (how === "downloaded") toast("Saved the image — attach it in WhatsApp.");
    } catch (err) {
      // A cancelled share sheet is a normal user action, not a failure.
      if (!(err instanceof DOMException && err.name === "AbortError")) {
        toast(err instanceof Error ? err.message : "Could not create the image.", "error");
      }
    } finally {
      setBusy(null);
    }
  }

  const sentCount = receipts.filter((r) => sent[r.receiptNo]).length;

  return (
    <div>
      <PageHeader
        title="Receipts from a list"
        subtitle="Paste the collection list, check what it read, then send each contributor their receipt or print the lot."
      />

      <Card className="p-4 sm:p-5">
        <Field
          label="Paste the list"
          hint="One per line. “12. Name – ₹501” or “Name (N-130) - 501” both work; the numbering is ignored."
        >
          <textarea
            className="field min-h-52 font-mono text-[0.8125rem] leading-relaxed"
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder={PLACEHOLDER}
            spellCheck={false}
          />
        </Field>

        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          <Field label="Date on every receipt">
            <input
              className="field"
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
            />
          </Field>
          <Field label="Start receipt number" hint={`Numbered ${prefix}/${fy}/…`}>
            <input
              className="field tnum"
              type="number"
              min={1}
              value={startNo}
              onChange={(e) => setStartNo(Math.max(1, Number(e.target.value) || 1))}
            />
          </Field>
        </div>
      </Card>

      {parsed.problems.length ? (
        <Card className="mt-4 border-debit/30 bg-debit-soft/40 p-4">
          <p className="text-[0.8125rem] font-semibold text-debit">
            {parsed.problems.length} line{parsed.problems.length === 1 ? "" : "s"} couldn&apos;t be
            read — no receipt for these
          </p>
          <ul className="mt-1.5 space-y-1">
            {parsed.problems.map((p) => (
              <li key={p.line} className="text-xs leading-snug text-debit">
                <span className="tnum font-medium">Line {p.line}:</span> {p.reason}{" "}
                <span className="text-debit/70">“{p.raw}”</span>
              </li>
            ))}
          </ul>
        </Card>
      ) : null}

      {duplicates.size ? (
        <Card className="mt-4 border-warn/30 bg-warn-soft/40 p-4">
          <p className="text-[0.8125rem] font-semibold text-warn">
            The same name appears more than once
          </p>
          <ul className="mt-1.5 space-y-1">
            {[...duplicates.values()].map((rows) => (
              <li key={`${rows[0].name}-${rows[0].line}`} className="text-xs leading-snug text-warn">
                <span className="font-medium">{rows[0].name}</span> on lines{" "}
                {rows.map((r) => r.line).join(", ")} — {rows.map((r) => money(r.amount)).join(" and ")}.
                Two people with the same name, or one entered twice?
              </li>
            ))}
          </ul>
        </Card>
      ) : null}

      {receipts.length ? (
        <div className="mt-5">
          <Card className="p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <p className="text-sm font-semibold text-ink">
                  {receipts.length} receipts · {money(parsed.total)}
                </p>
                <p className="tnum mt-0.5 text-xs text-ink-soft">
                  {receipts[0].receiptNo} to {receipts[receipts.length - 1].receiptNo}
                  {sentCount ? ` · ${sentCount} sent` : ""}
                </p>
              </div>
              <Button variant="secondary" onClick={() => window.print()}>
                Print all
              </Button>
            </div>
          </Card>

          <div className="mt-4">
            <SectionTitle>Add a number, then send</SectionTitle>
            <Card className="divide-y divide-line">
              {receipts.map((r) => (
                <div key={r.receiptNo} className="flex flex-wrap items-center gap-3 px-4 py-3">
                  <div className="min-w-[10rem] flex-1">
                    <p className="text-sm font-medium text-ink">
                      {r.name}
                      {r.wing || r.flat ? (
                        <span className="tnum ml-1.5 text-xs font-normal text-ink-soft">
                          {[r.wing, r.flat].filter(Boolean).join("-")}
                        </span>
                      ) : null}
                    </p>
                    <p className="tnum mt-0.5 text-xs text-ink-faint">
                      {r.receiptNo} · {money(r.amount)}
                    </p>
                  </div>

                  <input
                    className="field tnum w-40"
                    type="tel"
                    inputMode="numeric"
                    placeholder="WhatsApp no."
                    value={numbers[r.receiptNo] ?? ""}
                    onChange={(e) =>
                      setNumbers((n) => ({ ...n, [r.receiptNo]: e.target.value }))
                    }
                  />

                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      onClick={() => sendText(r)}
                      disabled={!numbers[r.receiptNo]?.trim()}
                    >
                      Send
                    </Button>
                    <Button
                      size="sm"
                      variant="secondary"
                      onClick={() => void sendImage(r)}
                      disabled={busy === r.receiptNo}
                    >
                      {busy === r.receiptNo ? "…" : "Image"}
                    </Button>
                    {sent[r.receiptNo] ? (
                      <span className="text-xs font-medium text-credit">✓</span>
                    ) : null}
                  </div>
                </div>
              ))}
            </Card>
            <p className="mt-2 text-xs leading-relaxed text-ink-faint">
              <strong>Send</strong> opens that person&apos;s WhatsApp chat with the receipt details
              typed out — one tap. <strong>Image</strong> shares the receipt picture in your printed
              design, but WhatsApp won&apos;t let a link carry a file, so you pick the contact
              yourself.
            </p>
          </div>
        </div>
      ) : null}
    </div>
  );
}
