-- Migration 005 — food coupons.
--
-- Run in the Supabase SQL Editor. Safe to re-run.
--
-- Residents register once per flat and get a QR. At the counter a volunteer
-- points a phone camera at it, the coupon page opens, and they record how many
-- of that family are eating now.
--
-- A coupon is a balance, not a switch: five allowed, three served, two left.
-- Families arrive in batches, and a used/unused flag would either turn away the
-- second batch or let the first eat five times.

create table if not exists public.food_coupons (
  id          uuid primary key default gen_random_uuid(),
  -- Short and unambiguous when read aloud at a noisy counter. Generated by the
  -- server; see new_coupon_code below.
  code        text not null unique,
  activity_id uuid references public.activities (id) on delete cascade,
  name        text not null,
  wing        text,
  flat        text,
  -- Not public. A coupon page shows who it belongs to, never how to ring them.
  mobile      text,
  members     integer not null check (members between 1 and 30),
  -- Kept on the row as well as in the log, so the counter can read a balance
  -- without summing history on every scan.
  served      integer not null default 0 check (served >= 0),
  -- Issued at the counter to someone with no coupon, rather than registered.
  walk_in     boolean not null default false,
  created_at  timestamptz not null default now()
);

-- One coupon per flat per activity. Partial, because a walk-in may have no
-- flat number and several such rows must be allowed to coexist.
create unique index if not exists food_coupons_one_per_flat
  on public.food_coupons (activity_id, upper(wing), flat)
  where wing is not null and flat is not null;

create index if not exists food_coupons_code_idx on public.food_coupons (code);

/**
 * Every serving, individually.
 *
 * The running total on the coupon answers "can they eat"; this answers "when
 * did the queue peak", which is what tells the committee whether to open a
 * second counter next year.
 */
create table if not exists public.food_servings (
  id        uuid primary key default gen_random_uuid(),
  coupon_id uuid not null references public.food_coupons (id) on delete cascade,
  count     integer not null check (count > 0),
  served_at timestamptz not null default now()
);

create index if not exists food_servings_at_idx on public.food_servings (served_at);
create index if not exists food_servings_coupon_idx on public.food_servings (coupon_id);

-- How many members one coupon may cover. On the society row so the committee
-- can change it during the event without a redeploy.
alter table public.societies
  add column if not exists max_coupon_members integer not null default 6;

-- ------------------------------------------------------------- code issue --

/**
 * A short code for the QR.
 *
 * Excludes 0/O and 1/I/L: these get read aloud across a serving counter, and a
 * code nobody can dictate over noise is a code that wastes everyone's time.
 */
create or replace function public.new_coupon_code()
returns text
language plpgsql
volatile
set search_path = ''
as $$
declare
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  candidate text;
  i int;
begin
  loop
    candidate := '';
    for i in 1..6 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    exit when not exists (select 1 from public.food_coupons where code = candidate);
  end loop;
  return candidate;
end;
$$;

create or replace function public.assign_coupon_code()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.code is null or new.code = '' then
    new.code := public.new_coupon_code();
  end if;
  return new;
end;
$$;

drop trigger if exists food_coupons_assign_code on public.food_coupons;
create trigger food_coupons_assign_code
  before insert on public.food_coupons
  for each row execute function public.assign_coupon_code();

-- ---------------------------------------------------------------- serving --

/**
 * Records a serving and returns the new balance.
 *
 * Does the check and the increment in one statement. Two volunteers scanning
 * the same coupon at the same moment would otherwise both read "2 remaining"
 * and both serve 2 — the row is locked for the duration so the second sees the
 * first's result.
 *
 * Returns a row rather than raising, so the counter can show "already fully
 * served" as an ordinary outcome instead of an error.
 */
create or replace function public.serve_coupon(p_code text, p_count integer)
returns table (ok boolean, reason text, members integer, served integer, remaining integer)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  c public.food_coupons%rowtype;
begin
  if p_count is null or p_count < 1 then
    return query select false, 'Count must be at least one', 0, 0, 0;
    return;
  end if;

  select * into c from public.food_coupons where code = upper(p_code) for update;

  if not found then
    return query select false, 'No such coupon', 0, 0, 0;
    return;
  end if;

  if c.served + p_count > c.members then
    return query select false,
      case when c.served >= c.members
           then 'Already fully served'
           else 'Only ' || (c.members - c.served) || ' left on this coupon' end,
      c.members, c.served, c.members - c.served;
    return;
  end if;

  update public.food_coupons set served = served + p_count where id = c.id;
  insert into public.food_servings (coupon_id, count) values (c.id, p_count);

  return query select true, 'Served'::text, c.members, c.served + p_count,
                      c.members - c.served - p_count;
end;
$$;

-- ------------------------------------------------------------------- RLS ---
--
-- Neither table is reachable from a browser. Registration, lookup and serving
-- all go through server routes holding the service key, because a resident
-- must be able to create a coupon without being able to read the whole list —
-- which would hand anyone the name, flat and mobile of every family in the
-- society.

alter table public.food_coupons  enable row level security;
alter table public.food_servings enable row level security;

revoke all on public.food_coupons  from anon, authenticated;
revoke all on public.food_servings from anon, authenticated;

-- Counts for the live dashboard, with no personal data in them at all.
create or replace view public.food_summary as
select
  count(*)::int                                as coupons,
  coalesce(sum(members), 0)::int               as people_registered,
  coalesce(sum(served), 0)::int                as people_served,
  count(*) filter (where served > 0)::int      as coupons_started,
  count(*) filter (where served >= members)::int as coupons_complete,
  count(*) filter (where walk_in)::int         as walk_ins
from public.food_coupons;

grant select on public.food_summary to anon, authenticated;

select 'food coupons ready' as status;
